# Generated by Django 3.2.6 on 2021-08-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('desc', models.TextField(default='')),
                ('image', models.ImageField(default='', upload_to='')),
                ('date', models.DateTimeField(default='')),
                ('posted_by', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
