# Generated by Django 3.2.6 on 2021-08-29 11:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('desc', ckeditor.fields.RichTextField(default='')),
                ('image', models.ImageField(default='', upload_to='')),
                ('date', models.DateTimeField()),
                ('posted_by', models.CharField(default='Kshitij Budholiya', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='comme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postid', models.CharField(default='', max_length=1000)),
                ('name', models.CharField(default='', max_length=100)),
                ('comment', models.TextField(default='')),
                ('dt', models.DateTimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('desc', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
